# @package _global_
defaults:
  - /trainer: default
  - /loader: full_test
  - /dataset: full_test
  - /task: full_test
  - /optimizer: adamw
  - /scheduler: plateau

train:
  monitor: val/loss # Needed for plateau scheduler
  mode: min

encoder: linear

decoder:
  _name_: sequence
  mode: last
